// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['mqtt']['MqttService']['Connect'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['mqtt']['MqttService']['Disconnect'](arg1);
}

export function GetConnections() {
  return window['go']['mqtt']['MqttService']['GetConnections']();
}

export function Publish(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['mqtt']['MqttService']['Publish'](arg1, arg2, arg3, arg4, arg5);
}

export function SetContext(arg1) {
  return window['go']['mqtt']['MqttService']['SetContext'](arg1);
}

export function Shutdown() {
  return window['go']['mqtt']['MqttService']['Shutdown']();
}

export function Subscribe(arg1, arg2, arg3) {
  return window['go']['mqtt']['MqttService']['Subscribe'](arg1, arg2, arg3);
}

export function Unsubscribe(arg1, arg2) {
  return window['go']['mqtt']['MqttService']['Unsubscribe'](arg1, arg2);
}
