// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mqtt} from '../models';
import {context} from '../models';

export function Connect(arg1:mqtt.ConnectionConfig):Promise<string>;

export function Disconnect(arg1:string):Promise<void>;

export function GetConnections():Promise<Array<mqtt.ConnectionStatus>>;

export function Publish(arg1:string,arg2:string,arg3:string,arg4:number,arg5:boolean):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Shutdown():Promise<void>;

export function Subscribe(arg1:string,arg2:string,arg3:number):Promise<void>;

export function Unsubscribe(arg1:string,arg2:string):Promise<void>;
