// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {http} from '../models';
import {context} from '../models';

export function AddFolder(arg1:string,arg2:string,arg3:string):Promise<http.TreeItem>;

export function AddRequest(arg1:string,arg2:string,arg3:http.HttpRequest):Promise<http.TreeItem>;

export function CreateCollection(arg1:string):Promise<http.Collection>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteItem(arg1:string,arg2:string):Promise<void>;

export function GetCollections():Promise<Array<http.Collection>>;

export function RenameCollection(arg1:string,arg2:string):Promise<void>;

export function RenameItem(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendRequest(arg1:http.HttpRequest):Promise<http.HttpResponse>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Shutdown():Promise<void>;

export function UpdateRequest(arg1:string,arg2:http.HttpRequest):Promise<void>;
