// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFolder(arg1, arg2, arg3) {
  return window['go']['http']['HttpService']['AddFolder'](arg1, arg2, arg3);
}

export function AddRequest(arg1, arg2, arg3) {
  return window['go']['http']['HttpService']['AddRequest'](arg1, arg2, arg3);
}

export function CreateCollection(arg1) {
  return window['go']['http']['HttpService']['CreateCollection'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['http']['HttpService']['DeleteCollection'](arg1);
}

export function DeleteItem(arg1, arg2) {
  return window['go']['http']['HttpService']['DeleteItem'](arg1, arg2);
}

export function GetCollections() {
  return window['go']['http']['HttpService']['GetCollections']();
}

export function RenameCollection(arg1, arg2) {
  return window['go']['http']['HttpService']['RenameCollection'](arg1, arg2);
}

export function RenameItem(arg1, arg2, arg3) {
  return window['go']['http']['HttpService']['RenameItem'](arg1, arg2, arg3);
}

export function SendRequest(arg1) {
  return window['go']['http']['HttpService']['SendRequest'](arg1);
}

export function SetContext(arg1) {
  return window['go']['http']['HttpService']['SetContext'](arg1);
}

export function Shutdown() {
  return window['go']['http']['HttpService']['Shutdown']();
}

export function UpdateRequest(arg1, arg2) {
  return window['go']['http']['HttpService']['UpdateRequest'](arg1, arg2);
}
