// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFolder(arg1, arg2, arg3) {
  return window['go']['adapters']['HTTPHandler']['AddFolder'](arg1, arg2, arg3);
}

export function AddRequest(arg1, arg2, arg3) {
  return window['go']['adapters']['HTTPHandler']['AddRequest'](arg1, arg2, arg3);
}

export function CancelRequest(arg1) {
  return window['go']['adapters']['HTTPHandler']['CancelRequest'](arg1);
}

export function CreateCollection(arg1) {
  return window['go']['adapters']['HTTPHandler']['CreateCollection'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['adapters']['HTTPHandler']['DeleteCollection'](arg1);
}

export function DeleteItem(arg1, arg2) {
  return window['go']['adapters']['HTTPHandler']['DeleteItem'](arg1, arg2);
}

export function GetCollections() {
  return window['go']['adapters']['HTTPHandler']['GetCollections']();
}

export function GetRootItems() {
  return window['go']['adapters']['HTTPHandler']['GetRootItems']();
}

export function GetSidebarLayout() {
  return window['go']['adapters']['HTTPHandler']['GetSidebarLayout']();
}

export function MoveItem(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['adapters']['HTTPHandler']['MoveItem'](arg1, arg2, arg3, arg4, arg5);
}

export function MoveItemToSidebar(arg1, arg2, arg3) {
  return window['go']['adapters']['HTTPHandler']['MoveItemToSidebar'](arg1, arg2, arg3);
}

export function MoveSidebarEntry(arg1, arg2, arg3) {
  return window['go']['adapters']['HTTPHandler']['MoveSidebarEntry'](arg1, arg2, arg3);
}

export function OpenFilePicker() {
  return window['go']['adapters']['HTTPHandler']['OpenFilePicker']();
}

export function RenameCollection(arg1, arg2) {
  return window['go']['adapters']['HTTPHandler']['RenameCollection'](arg1, arg2);
}

export function RenameItem(arg1, arg2, arg3) {
  return window['go']['adapters']['HTTPHandler']['RenameItem'](arg1, arg2, arg3);
}

export function SaveResponseBase64(arg1, arg2) {
  return window['go']['adapters']['HTTPHandler']['SaveResponseBase64'](arg1, arg2);
}

export function SaveResponseBody(arg1, arg2) {
  return window['go']['adapters']['HTTPHandler']['SaveResponseBody'](arg1, arg2);
}

export function SendRequest(arg1) {
  return window['go']['adapters']['HTTPHandler']['SendRequest'](arg1);
}

export function UpdateRequest(arg1, arg2) {
  return window['go']['adapters']['HTTPHandler']['UpdateRequest'](arg1, arg2);
}
