// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {httpdomain} from '../models';

export function CancelRequest():Promise<void>;

export function AddFolder(arg1:string,arg2:string,arg3:string):Promise<httpdomain.TreeItem>;

export function AddRequest(arg1:string,arg2:string,arg3:httpdomain.HttpRequest):Promise<httpdomain.TreeItem>;

export function CreateCollection(arg1:string):Promise<httpdomain.Collection>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteItem(arg1:string,arg2:string):Promise<void>;

export function GetCollections():Promise<Array<httpdomain.Collection>>;

export function RenameCollection(arg1:string,arg2:string):Promise<void>;

export function RenameItem(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendRequest(arg1:httpdomain.HttpRequest):Promise<httpdomain.HttpResponse>;

export function UpdateRequest(arg1:string,arg2:httpdomain.HttpRequest):Promise<void>;
