// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {adapters} from '../models';

export function AddFolder(arg1:string,arg2:string,arg3:string):Promise<adapters.TreeItem>;

export function AddRequest(arg1:string,arg2:string,arg3:adapters.HttpRequest):Promise<adapters.TreeItem>;

export function CancelRequest(arg1:string):Promise<void>;

export function CreateCollection(arg1:string):Promise<adapters.Collection>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteItem(arg1:string,arg2:string):Promise<void>;

export function GetCollections():Promise<Array<adapters.Collection>>;

export function GetRootItems():Promise<Array<adapters.TreeItem>>;

export function MoveItem(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function OpenFilePicker():Promise<string>;

export function RenameCollection(arg1:string,arg2:string):Promise<void>;

export function RenameItem(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendRequest(arg1:adapters.HttpRequest):Promise<adapters.HttpResponse>;

export function UpdateRequest(arg1:string,arg2:adapters.HttpRequest):Promise<void>;
