// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFolder(arg1, arg2, arg3) {
  return window['go']['adapters']['HttpHandler']['AddFolder'](arg1, arg2, arg3);
}

export function AddRequest(arg1, arg2, arg3) {
  return window['go']['adapters']['HttpHandler']['AddRequest'](arg1, arg2, arg3);
}

export function CancelRequest(arg1) {
  return window['go']['adapters']['HttpHandler']['CancelRequest'](arg1);
}

export function CreateCollection(arg1) {
  return window['go']['adapters']['HttpHandler']['CreateCollection'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['adapters']['HttpHandler']['DeleteCollection'](arg1);
}

export function DeleteItem(arg1, arg2) {
  return window['go']['adapters']['HttpHandler']['DeleteItem'](arg1, arg2);
}

export function GetCollections() {
  return window['go']['adapters']['HttpHandler']['GetCollections']();
}

export function GetRootItems() {
  return window['go']['adapters']['HttpHandler']['GetRootItems']();
}

export function MoveItem(arg1, arg2, arg3, arg4) {
  return window['go']['adapters']['HttpHandler']['MoveItem'](arg1, arg2, arg3, arg4);
}

export function OpenFilePicker() {
  return window['go']['adapters']['HttpHandler']['OpenFilePicker']();
}

export function RenameCollection(arg1, arg2) {
  return window['go']['adapters']['HttpHandler']['RenameCollection'](arg1, arg2);
}

export function RenameItem(arg1, arg2, arg3) {
  return window['go']['adapters']['HttpHandler']['RenameItem'](arg1, arg2, arg3);
}

export function SendRequest(arg1) {
  return window['go']['adapters']['HttpHandler']['SendRequest'](arg1);
}

export function UpdateRequest(arg1, arg2) {
  return window['go']['adapters']['HttpHandler']['UpdateRequest'](arg1, arg2);
}
