// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {adapters} from '../models';

export function Log(arg1:adapters.LogEntry):Promise<void>;
