// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['adapters']['MQTTHandler']['Connect'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['adapters']['MQTTHandler']['DeleteProfile'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['adapters']['MQTTHandler']['Disconnect'](arg1);
}

export function GetConnections() {
  return window['go']['adapters']['MQTTHandler']['GetConnections']();
}

export function GetProfiles() {
  return window['go']['adapters']['MQTTHandler']['GetProfiles']();
}

export function Publish(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['adapters']['MQTTHandler']['Publish'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveProfile(arg1) {
  return window['go']['adapters']['MQTTHandler']['SaveProfile'](arg1);
}

export function Shutdown() {
  return window['go']['adapters']['MQTTHandler']['Shutdown']();
}

export function Subscribe(arg1, arg2, arg3) {
  return window['go']['adapters']['MQTTHandler']['Subscribe'](arg1, arg2, arg3);
}

export function Unsubscribe(arg1, arg2) {
  return window['go']['adapters']['MQTTHandler']['Unsubscribe'](arg1, arg2);
}
