// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mqttdomain} from '../models';

export function Connect(arg1:mqttdomain.ConnectionConfig):Promise<string>;

export function DeleteProfile(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function GetConnections():Promise<Array<mqttdomain.ConnectionStatus>>;

export function GetProfiles():Promise<Array<mqttdomain.BrokerProfile>>;

export function Publish(arg1:string,arg2:string,arg3:string,arg4:number,arg5:boolean):Promise<void>;

export function SaveProfile(arg1:mqttdomain.BrokerProfile):Promise<void>;

export function Shutdown():Promise<void>;

export function Subscribe(arg1:string,arg2:string,arg3:number):Promise<void>;

export function Unsubscribe(arg1:string,arg2:string):Promise<void>;
