// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {adapters} from '../models';

export function GetRecents():Promise<Array<adapters.OpenApiRecent>>;

export function MoveRecent(arg1:string,arg2:number):Promise<void>;

export function OpenFilePicker():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function RemoveRecent(arg1:string):Promise<void>;

export function SaveFileAs(arg1:string,arg2:string):Promise<string>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
