// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFilePicker() {
  return window['go']['adapters']['OpenAPIHandler']['OpenFilePicker']();
}

export function ReadFile(arg1) {
  return window['go']['adapters']['OpenAPIHandler']['ReadFile'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['adapters']['OpenAPIHandler']['WriteFile'](arg1, arg2);
}
