// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRecents() {
  return window['go']['adapters']['OpenAPIHandler']['GetRecents']();
}

export function MoveRecent(arg1, arg2) {
  return window['go']['adapters']['OpenAPIHandler']['MoveRecent'](arg1, arg2);
}

export function OpenFilePicker() {
  return window['go']['adapters']['OpenAPIHandler']['OpenFilePicker']();
}

export function ReadFile(arg1) {
  return window['go']['adapters']['OpenAPIHandler']['ReadFile'](arg1);
}

export function RemoveRecent(arg1) {
  return window['go']['adapters']['OpenAPIHandler']['RemoveRecent'](arg1);
}

export function SaveFileAs(arg1, arg2) {
  return window['go']['adapters']['OpenAPIHandler']['SaveFileAs'](arg1, arg2);
}

export function WriteFile(arg1, arg2) {
  return window['go']['adapters']['OpenAPIHandler']['WriteFile'](arg1, arg2);
}
