// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTarget(arg1) {
  return window['go']['adapters']['UDPHandler']['DeleteTarget'](arg1);
}

export function GetListeners() {
  return window['go']['adapters']['UDPHandler']['GetListeners']();
}

export function GetTargets() {
  return window['go']['adapters']['UDPHandler']['GetTargets']();
}

export function SaveTarget(arg1) {
  return window['go']['adapters']['UDPHandler']['SaveTarget'](arg1);
}

export function Send(arg1) {
  return window['go']['adapters']['UDPHandler']['Send'](arg1);
}

export function Shutdown() {
  return window['go']['adapters']['UDPHandler']['Shutdown']();
}

export function StartListen(arg1, arg2) {
  return window['go']['adapters']['UDPHandler']['StartListen'](arg1, arg2);
}

export function StopListen(arg1) {
  return window['go']['adapters']['UDPHandler']['StopListen'](arg1);
}
