// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTarget(arg1) {
  return window['go']['adapters']['UdpHandler']['DeleteTarget'](arg1);
}

export function GetListeners() {
  return window['go']['adapters']['UdpHandler']['GetListeners']();
}

export function GetTargets() {
  return window['go']['adapters']['UdpHandler']['GetTargets']();
}

export function SaveTarget(arg1) {
  return window['go']['adapters']['UdpHandler']['SaveTarget'](arg1);
}

export function Send(arg1) {
  return window['go']['adapters']['UdpHandler']['Send'](arg1);
}

export function Shutdown() {
  return window['go']['adapters']['UdpHandler']['Shutdown']();
}

export function StartListen(arg1, arg2) {
  return window['go']['adapters']['UdpHandler']['StartListen'](arg1, arg2);
}

export function StopListen(arg1) {
  return window['go']['adapters']['UdpHandler']['StopListen'](arg1);
}
