// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {udpdomain} from '../models';

export function DeleteTarget(arg1:string):Promise<void>;

export function GetListeners():Promise<Array<udpdomain.UdpListenSession>>;

export function GetTargets():Promise<Array<udpdomain.UdpTarget>>;

export function SaveTarget(arg1:udpdomain.UdpTarget):Promise<udpdomain.UdpTarget>;

export function Send(arg1:udpdomain.UdpSendRequest):Promise<udpdomain.UdpSendResult>;

export function Shutdown():Promise<void>;

export function StartListen(arg1:number,arg2:string):Promise<udpdomain.UdpListenSession>;

export function StopListen(arg1:string):Promise<void>;
