// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {adapters} from '../models';

export function DeleteTarget(arg1:string):Promise<void>;

export function GetListeners():Promise<Array<adapters.UdpListenSession>>;

export function GetTargets():Promise<Array<adapters.UdpTarget>>;

export function SaveTarget(arg1:adapters.UdpTarget):Promise<adapters.UdpTarget>;

export function Send(arg1:adapters.UdpSendRequest):Promise<adapters.UdpSendResult>;

export function Shutdown():Promise<void>;

export function StartListen(arg1:number,arg2:string):Promise<adapters.UdpListenSession>;

export function StopListen(arg1:string):Promise<void>;
