// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {udpdomain} from '../models';

export function DeleteTarget(arg1:string):Promise<void>;

export function GetListeners():Promise<Array<udpdomain.UDPListenSession>>;

export function GetTargets():Promise<Array<udpdomain.UDPTarget>>;

export function SaveTarget(arg1:udpdomain.UDPTarget):Promise<udpdomain.UDPTarget>;

export function Send(arg1:udpdomain.UDPSendRequest):Promise<udpdomain.UDPSendResult>;

export function Shutdown():Promise<void>;

export function StartListen(arg1:number,arg2:string):Promise<udpdomain.UDPListenSession>;

export function StopListen(arg1:string):Promise<void>;
